### ISSUE TITLE
Fails with PostgreSQL 15

### ISSUE THREAD

**Issue by andinus** [maettu/db-migration-simple#1]
```
DBDish::Pg: Error: syntax error at or near "'db-migrations-simple-meta'" (7)
  in method prepare at /home/rocky/.raku/sources/FA31B77330A4A16EF68E6C6DDD869B9C0F2068FE (DBDish::Pg::Connection) line 46
  in method execute at /home/rocky/.raku/sources/7D597CC34705B2E5A7F16F6E23CC83C4B818626D (DBDish::Connection) line 131
  in method do at /home/rocky/.raku/sources/7D597CC34705B2E5A7F16F6E23CC83C4B818626D (DBDish::Connection) line 144
  in method init-meta-table at /home/rocky/.raku/sources/115EF7B9694052BAEB1736105609F80C8BEA2846 (DB::Migration::Simple) line 113
  in method current-version at /home/rocky/.raku/sources/115EF7B9694052BAEB1736105609F80C8BEA2846 (DB::Migration::Simple) line 23
```

Removing quotes should do the trick.

**Comment by maettu** [comment]
Are you interested in adopting this little module?

I have written it a couple of years ago and never used in a long time.

About "removing quotes": I do believe I had a discussion back then about those quotes, but I do not remember the details.. Have asked.

**Comment by andinus** [comment]
Hello, it seems to be mostly complete. I'll be interested in getting it up to date however. I'll make a few PRs then to cleanup things, and then we can publish it. 

I'll be using this module for a project. I was wondering if schema changes can be tracked in separate files like this node module: https://github.com/thomwright/postgres-migrations but the current approach also works fine. 

Edit: Yes, I'll be interested in adopting it.

**Comment by maettu** [comment]
OK, wonderful. Unfortunately, I don't know how to transfer it to you :-)

**Comment by andinus** [comment]
You can just add me as contributor to this repository, as for publishing the module, currently it's published on CPAN. Raku is moving to `zef` ecosystem (https://raku.land/stats), I can publish the latest version there and it should be fine, just that the 'author' field will be different.

**Comment by maettu** [comment]
Great, had github send you an invite. Looking forward to your changes! Thanks a lot.

**Comment by andinus** [comment]
Thanks :)

**Comment by andinus** [comment]
What we need here is double quotes instead of single quotes.

> SQL in general (i.e. ISO/ANSI SQL) has a different set of quotes: double quotes are for delimited identifiers, e.g. "tablename", and single quotes are for literals, e.g. 'this is a some text'.

There is a catch to that for MySQL: https://stackoverflow.com/a/14123649/15322099

But double quotes seem like the best choice. I'll test this in PostgreSQL, MariaDB, SQLite and then push this change.

**Comment by maettu** [comment]
I don't know what the quotes are for, actually. If it was to "quote" "unsafe input", then it would need some "quote-meta"* of the string passed in, not quotes around it, no?

*escaping problematic characters like the quote etc to avoid injections.

But then, the table name here should never be user input, anyway.

**Comment by andinus** [comment]
In case of PostgreSQL double quotes makes identifiers case sensitive (https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS).

i.e. without quotes myTABLE == MYTABLE, with quotes that's  not the case.

We can skip them as well, anyways this is for our internal table so it doesn't matter. We don't have to worry about escaping anything or even double quoting it.

**Comment by andinus** [comment]
Made a push, tested against PostgreSQL v15, it seems to be working fine. Tested with some minor changes in `migrations` file that is used for testing SQLite.

Migrations file used for testing PostgreSQL:
```
-- 1 up # comment
CREATE TABLE table_version_1( /* comment */
    # comment
    /* or, SQL style comment */
    id SERIAL PRIMARY KEY,
    msg TEXT
); ;
INSERT INTO table_version_1 (msg) VALUES('This is version 1');

# comment

--1 down
DROP TABLE table_version_1;


-- 2 up
CREATE TABLE table_version_2 (msg TEXT);
INSERT INTO table_version_2 VALUES ('This is version 2');

-- 2 down
DROP TABLE table_version_2;

-- 3 up
CREATE TABLE table_version_3 (msg TEXT);

-- 3 down
DROP TABLE table_version_3;
```

**Comment by maettu** [comment]
Thank you!

**Comment by andinus** [comment]
Should I make a release on zef? I'll also rename `.p6` to `.raku` & others.

**Comment by maettu** [comment]
Please do what you think is best. I am happy you find this module useful and are ready to work on it.

**Comment by maettu** [comment]
When you have a release, I'll probably delete it on the CPAN, no?

**Comment by andinus** [comment]
Okay :)

I think it's fine to keep the CPAN release, doesn't affect anything.
